## Import all Library

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [88]:
df=pd.read_excel('data_processing.xlsx')

In [89]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1      NaN  27.0  48000.0       Yes
2  Germany   NaN  54000.0        No
3    Spain  39.0      NaN        No
4  Germany   NaN  64000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  39.0  52000.0        No
7   France  48.0      NaN       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [90]:
x=df.iloc[:,:-1].values

In [91]:
x

array([['France', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany', nan, 54000.0],
       ['Spain', 39.0, nan],
       ['Germany', nan, 64000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, nan],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [92]:
y=df.iloc[:,-1].values

In [93]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Missing Value Treatment

In [94]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values=np.nan,strategy='most_frequent')

In [95]:
si=si.fit(x[:,:1])

In [96]:
x[:,:1]=si.transform(x[:,:1])

In [97]:
x

array([['France', 44.0, 72000.0],
       ['France', 27.0, 48000.0],
       ['Germany', nan, 54000.0],
       ['Spain', 39.0, nan],
       ['Germany', nan, 64000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, nan],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [101]:
si=SimpleImputer(missing_values=np.nan,strategy='mean')
si=si.fit(x[:,1:2])
x[:,1:2]=si.transform(x[:,1:2])

In [102]:
x

array([['France', 44.0, 72000.0],
       ['France', 27.0, 48000.0],
       ['Germany', 39.875, 54000.0],
       ['Spain', 39.0, 62250.0],
       ['Germany', 39.875, 64000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 62250.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [103]:
sii=SimpleImputer(missing_values=np.nan,strategy='mean')
sii=sii.fit(x[:,2:3])
x[:,2:3]=sii.transform(x[:,2:3])

In [104]:
x

array([['France', 44.0, 72000.0],
       ['France', 27.0, 48000.0],
       ['Germany', 39.875, 54000.0],
       ['Spain', 39.0, 62250.0],
       ['Germany', 39.875, 64000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 62250.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Label Encoding

In [105]:
from sklearn.preprocessing import LabelEncoder

In [106]:
label_x=LabelEncoder()

In [107]:
x[:,0]=label_x.fit_transform(x[:,0])

In [108]:
x

array([[0, 44.0, 72000.0],
       [0, 27.0, 48000.0],
       [1, 39.875, 54000.0],
       [2, 39.0, 62250.0],
       [1, 39.875, 64000.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 62250.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

# One Hot Encoding

In [109]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(),[0])],remainder='passthrough')

In [110]:
x=ct.fit_transform(x)

In [111]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 39.875, 54000.0],
       [0.0, 0.0, 1.0, 39.0, 62250.0],
       [0.0, 1.0, 0.0, 39.875, 64000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 62250.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [112]:
#label Encoding of Y (dependent variable)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [113]:
from sklearn.preprocessing import StandardScaler

In [114]:
ss=StandardScaler()
x_std=ss.fit_transform(x)
x_std=pd.DataFrame(x_std)
x_std

0         1    2         3         4
0  1.0 -0.654654 -0.5  0.664912  1.002707
1  1.0 -0.654654 -0.5 -2.075331 -1.465494
2 -1.0  1.527525 -0.5  0.000000 -0.848444
3 -1.0 -0.654654  2.0 -0.141042  0.000000
4 -1.0  1.527525 -0.5  0.000000  0.179973
5  1.0 -0.654654 -0.5 -0.785805 -0.437077
6 -1.0 -0.654654  2.0 -0.141042 -1.054127
7  1.0 -0.654654 -0.5  1.309675  0.000000
8 -1.0  1.527525 -0.5  1.632056  2.133965
9  1.0 -0.654654 -0.5 -0.463423  0.488498

### Using Standard Scaler , we are getting negative number so we will use Min max Scaler

In [115]:
from sklearn.preprocessing import MinMaxScaler

In [116]:
ms=MinMaxScaler()

In [117]:
x_ms=pd.DataFrame(ms.fit_transform(x))

In [118]:
x_ms

0    1    2         3         4
0  1.0  0.0  0.0  0.739130  0.685714
1  1.0  0.0  0.0  0.000000  0.000000
2  0.0  1.0  0.0  0.559783  0.171429
3  0.0  0.0  1.0  0.521739  0.407143
4  0.0  1.0  0.0  0.559783  0.457143
5  1.0  0.0  0.0  0.347826  0.285714
6  0.0  0.0  1.0  0.521739  0.114286
7  1.0  0.0  0.0  0.913043  0.407143
8  0.0  1.0  0.0  1.000000  1.000000
9  1.0  0.0  0.0  0.434783  0.542857